version: '3.7'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: veta@123
      MYSQL_DATABASE: veta_db
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234" ]
      timeout: 20s
      retries: 10
    ports:
        - "3308:3306"
    networks:
          - veta-network
  cattle-service:
    build: ../../veta/
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9898:9898"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/veta_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: veta@123
      SPRING_DATASOURCE_HOST: mysql
    networks:
      - veta-network
networks:
  veta-network:
    driver: bridge
